### ISSUE TITLE
Move crate versioning to top-level `Cargo.toml`

### ISSUE THREAD

**Issue by jbencin** [stacks-network/stacks-core#4105]
Recently I tried updating `wsts` and found that it failed to compile if not all workspace members used the same version of the crate. I fixed it by setting a common version for all workspace members in the top-level `Cargo.toml` file:

```toml
[workspace.dependencies]  
wsts = "5.0"
```

And in the workspace member `Cargo.toml` files:

```toml
[dependencies]
wsts = {workspace = true}
```

There are several crates that are used in multiple workspace members, and using different versions of them could lead to build or runtime errors. Most (all?) of these crates should be moved to the `[workspace.dependencies]` section
