### ISSUE TITLE
Stacks-signer cannot resolve hostnames for `node_host` config

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-core#4466]
The `node_host` value in the stacks-signer toml config can only be an IP:port and fails to resolve if given a hostname.

This makes the signer difficult to use in many environments. For example, here's a work-around required for a very simple docker-compose setup:
```yaml
  stacks-signer-2:
    build:
      context: .
      dockerfile: Dockerfile.stacks-node
    volumes:
      - ./signer-0.toml:/root/config.toml.in
    environment:
      STACKS_NODE_HOST: stacks-node:20443
      STACKS_SIGNER_ENDPOINT: 0.0.0.0:30002
      STACKS_CORE_EVENT_PORT: 3700
      STACKS_SIGNER_LOG_LEVEL: debug
      SIGNER_PRIVATE_KEY: ce109fee08860bb16337c76647dcbc02df0c06b455dd69bcf30af74d4eedd19301
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        # signer cannot resolve hostnames..
        export STACKS_NODE_HOST=$$(getent hosts $${STACKS_NODE_HOST%%:*} | awk '{ print $1 }'):$${STACKS_NODE_HOST##*:}
        echo "Updated STACKS_NODE_HOST to $$STACKS_NODE_HOST"
        envsubst < config.toml.in > config.toml
        exec stacks-signer run --config config.toml --reward-cycle 1
```
