### ISSUE TITLE
Avoid extraneous CI runs

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-core#4746]
Our _ci.yml_ currently includes the following trigger:

```yml
  pull_request_review:
    types:
      - submitted
```

This causes the CI to be rerun whenever a review is submitted. This is not needed and causes unnecessary delays and runner usage. The jobs are already guaranteed to be re-run when anything changes based on the `pull_request` triggers:

```yml
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
```
