### ISSUE TITLE
[CI] move rustfmt steps into the actions repo

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-core#4794]
currently:
```
  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@f3c84ee10bf5a86e7a5d607d487bf17d57670965 # v1.5.0
        with:
          components: rustfmt
          cache: false

      - name: Rustfmt
        id: rustfmt
        uses: stacks-network/actions/rustfmt@main
        with:
          alias: "fmt-stacks"
 ```
 
 I think we can modify this and make upgrading the action  versions easier in the future by moving the checking and rust steps to the https://github.com/stacks-network/actions/tree/main/rustfmt workflow. 
 the end result to teh ci.yml workflow would look like this (probably):
 ```
   rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - name: Rustfmt
        id: rustfmt
        uses: stacks-network/actions/rustfmt@main
        with:
          alias: "fmt-stacks"
```
