### ISSUE TITLE
Default Nakamoto timing settings for mainnet

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#5334]
This issue is a placeholder for discussion about setting the default nakamoto timing settings in preparation for nakamoto on mainnet.

There may be more settings than I'm listing here, so if folks have some settings that they think should be included for discussion, please reply:

Miner:

```toml
[miner]
nakamoto_attempt_time_ms = 5_000
min_time_between_blocks_ms = 1_000
```

Signer:

```toml
# if the first block proposal in a tenure doesn't arrive within 30 seconds, reject that tenure's
# proposals
first_proposal_burn_block_timing_secs = 30
# if the first block in a tenure is within 45 seconds of the next burnchain block,
#  allow the subsequent miner to reorg the prior miner.
block_proposal_timeout_ms = 45_000
```

The signer settings seem okay to me, but maybe deserve some more leniency with the first proposal: maybe 45 seconds for each?

The miner setting `nakamoto_attempt_time_ms` seems excessively aggressive. This will punish longer running TXs, and, I suspect, when the mempool is full, trade off too much "goodput" in block production. I think 10 or 20 seconds are probably better settings here.
